### ISSUE TITLE
Management - Add Delegated Trader

### ISSUE THREAD

**Issue by aggregatedfinance** [aggregatedfinance/agfi-dao#10]
_The modification to be made (e.g. add new DAO proposer):_

Add Telegram user @Eggwards as a delegated trader to the AGFI team.

Actions:

- Ed KYC and signs Delegated Trader agreement with DAO Custodian.
- Establish a shared wallet between the DAO Custodian and Ed.
- Transfer 50% of the current AGFI treasury value to the shared wallet.
- Release 10,000,000,000 AGFI to aggregatedfinance.eth to pay Ed on a bi-weekly basis according to the rules defined below. This amount will be paid to Ed until either the supply is exhausted or a second vote is performed to cancel the agreement with Ed.

_The purpose of the modification, and a justification as to requiring the modification to be made:_

Statement provided by proposed trader:

> I'm an experienced Computer scientist and have been working in the sector for several years. I've been learning and testing out crypto for almost 8 years and for the past 3 years I've specialised in making bots for various financial tasks several involving crypto and trading. Over these years I've built a keen interest in Blockchain and also a good eye for trading. Recently I've maintained an average of around 5% profit weekly which will increase when the bull runs start.
> 
> I'm putting this proposal forward because I believe I can help grow our treasury and build a sustainable profit stream for all AGFIers.
> 
> I believe managing around 50% of the current treasury will yield the best results.
> 
> Normally I trade for long term profits but due to recent market volatility I'll be using bots and leverage trading to make profits from smaller market fluctuations. Then as markets settle I'll move more towards safer more long term investments once again.
> 
> I'll personally be active and ready to react to any market changes as well as having bots and safety measures in place to catch large drops or unexpected events while I'm not actively checking the market. I'll be using a more aggressive style of trading with several daily trades and very short term leveraged positions.
> 
> While the treasury is low I'm happy to accept a percentage of 500m AGFI weekly. The percentage will be calculated as follows:
> If I make profit over 0% then I get full 500m but for any 1% loss I take 10% cut from payment. Up to a maximum of 10% loss where I'd lose 100% of the pay and wouldn't get any AGFI. This is because being payed when nothing was earned would negatively impact the value of AGFI and be dishonourable. Further more I won't be taking any commission on profits until we hit 500k in the treasury to maintain as much money in investments allowing for faster growth.

**Comment by Cryptobuzz1** [comment]
I am delighted with this proposal. Something the project is in desperate need off. I personally have no questions

**Comment by LeoKing7777** [comment]
Few questions- 1. Does this proposal not need to have Ed's wallet confirmed for payment? - also can we create bi- weekly payments rather than monthly? And who is going to keep and eye on the P/L? Otherwise happy to vote for this.

**Comment by aggregatedfinance** [comment]
> Few questions- 1. Does this proposal not need to have Ed's wallet confirmed for payment? - also can we create bi- weekly payments rather than monthly? And who is going to keep and eye on the P/L? Otherwise happy to vote for this.

The wallet address for payment is not needed as the proposal will release the AGFI to aggregatedfinance.eth. The DAO Custodian will send the individual payments as per the terms of release. If you want bi-weekly instead of monthly the proposal parameters can be changed.

**Comment by XxxRexxx** [comment]
i am against. handing over 50% of treasury to trader at this point don't sound good idea. also paying salary when AGFI in this condition and market condition also bad idea

**Comment by aggregatedfinance** [comment]
> i am against. handing over 50% of treasury to trader at this point don't sound good idea. also paying salary when AGFI in this condition and market condition also bad idea

If you're opposed to the suggested amount, what would you suggest as an alternative amount?

Also the salary paid in AGFI was agreed to by Ed, and is coming from uncirculating tokens held by the DAO. Is there an alternative that would be preferable?

**Comment by aggregatedfinance** [comment]
Telegram user name for Ed added to post description

**Comment by Melkorious** [comment]
This Proposal is clear to move to vote.

**Comment by LeoKing7777** [comment]
> i am against. handing over 50% of treasury to trader at this point don't sound good idea. also paying salary when AGFI in this condition and market condition also bad idea

There is no pay going out that will effect our volume or treasury- we have 100b in AGFI in circulation, it will cost us nothing to pay out 2bn for even 5 months - I.e 10bn and by then we can revise the payment method via the DAO if the Mcap has increased substantially.

**Comment by aggregatedfinance** [comment]
Proposal has been queued for voting on Tally:

https://www.tally.xyz/governance/eip155:1:0xD243F9aAfCf32e60b2e9D0FF016cf7f1552d5952/proposal/61880875031545605980403550342393706430487916577065522227371219184560334594066

**Comment by aggregatedfinance** [comment]
Vote has passed. Proposal now queued for execution: https://etherscan.io/tx/0x07f74acd35d95822c8f3e1fa8706adae7ba354f0297efa8f8341ddc2ee515bb4

**Comment by aggregatedfinance** [comment]
Proposal executed: https://etherscan.io/tx/0x62669ab1d47bf00084b8d1ba154fbc0bc2de637567be8abbb173e6e07ef0c7f6
