### ISSUE TITLE
Management - Close the Private Alpha Telegram channel

### ISSUE THREAD

**Issue by Zaphods-Ghost** [aggregatedfinance/agfi-dao#11]
The modification to be made (e.g. add new DAO proposer):

I propose the AGFI team close the ALPHA Private Telegram channel to increase the interactions in the Main(public) AGFI Telegram.

1. The ALPHA channel was meant for ALPHA from the project, for example a  _partnership whitelist Pre buy_.   This is a great idea, but that is not what the channel is being used for, it is being used as the main chat with 53 of the larger holders not interacting with the main TG channel/community at all.
2. With So much of the daily discussion happening in a PRIVATE channel, the main AGFI TG channel is basically dead.     This is very detrimental to the project, If just for the reason that prospective investors will join the channel and see no meaningful discussion for weeks.  Would you invest in AGFI with completely dead community.(or so it would seem as discussions are being held in a Private channel)
3. The whole Delegated trader Proposal was discussed/decided in the PRIVATE channel instead of the main AGFI channel where everyone can see the conversation and participate.     There was barely any discussion on the Github, because it was all discussed in the AAA channel.
4. When the projects decides to begin some AAA perks again, possibly reopen the Private channel.  

The purpose of the modification, and a justification as to requiring the modification to be made:

**Comment by mazza007** [comment]
.

**Comment by Melkorious** [comment]
This is an interesting Proposal, however I'm not sure a private Telegram Channel falls under the "jurisdiction" of the DAO.  The AGFI DAO can't compel others to conclude or commence private dialogues.

That said, considering how the channel is being used, and considering that vital discussions have been isolated to said channel, this Proposal does meet the criteria as 'valid', and can be advanced to vote.

**Comment by AGFITRUST** [comment]
This is a great proposal in my opinion, it will increase the volume on the original telegram group and make more people concern about AGFI even with small amount of token.

It's the purpose of AGFI to give to any holder a share on what's going on and what can happen to the project.

Thanks Zaphods-Ghost, I will support this proposal

**Comment by LeoKing7777** [comment]
I personally think that given the market condition it's vital to have all conversations in the main TG group especially if this is a "DAO Project" And any education or info should be shared at same advantage across all community members and sometimes that group could overlap and be misused for such information.

**Comment by AsgaaardFjord** [comment]
I agree to some extend. The AAA was one of the big perks to actually hold agfi with alpha news, presale opportunities and discussions with the trader/farmer.

Given the current state, none of the above is happening right now, we can close.

If AGFI gets his momentum again, it's necessary that the benefits are discussed in a private group again and not shared in the main group for everybody.

In short:

Everything related to everyone should be discussed in main channel 
The perks should be an incentive for 1bil holders and only shared in a private group.

**Comment by aggregatedfinance** [comment]
Proposal opened on Snapshot: https://snapshot.org/#/aggregatedfinance.eth/proposal/0xebf1d9b5843cb3fb6eee3df5b285ff1ecae8f8ee73c599339f5f740a8e72c63a

**Comment by aggregatedfinance** [comment]
Proposal passed. Alpha channel has had all permissions revoked so it can no longer be used.
