### ISSUE TITLE
Management - New Proposal Manager

### ISSUE THREAD

**Issue by AsgaaardFjord** [aggregatedfinance/agfi-dao#12]
With two proposal managers stepping down, I propose myself as a PM

TG name: asgaard
Githubname: asgaaardfjord

Timezone: UTC+2

Wallet address: 0x4e376b244FD8040435FBeB4F10bc4301482D89aA

Motivation: I have been a mod/admin for agfi since February and I have strong believe into this project.

**Comment by Melkorious** [comment]
Clear to advance to vote.

**Comment by aggregatedfinance** [comment]
Proposal Opened on Snapshot: https://snapshot.org/#/aggregatedfinance.eth/proposal/0xa02828f658a5f824e5cf582b2f0c0b94909ab02800471f02434b063a25bc0535

**Comment by aggregatedfinance** [comment]
Proposal passed vote. Address 0x4e376b244FD8040435FBeB4F10bc4301482D89aA granted CANCELLER_ROLE 0xfd643c72710c63c0180259aba6b2d05451e3591a24e58b62239378085726f783 on governor contract 0x97eee9c5b9a4b089813365ccf0315c4e9aa6f516

https://etherscan.io/tx/0x3e403e3c4e0662f07f1b2af151b487bb1c689a555d4490bf0cefcf12fc7e0960
