### ISSUE TITLE
Purchase 1000 HEC Tokens or maximum value $16000

### ISSUE THREAD

**Issue by Cryptobuzz1** [aggregatedfinance/agfi-dao#13]
The amount requested to transfer: upto $16000 usdc

To purchase 1000 HEC TOKENS on execution of the vote if passed. ( or the maximum of tokens for $16000 usdc funds to be released from diego wallet as this would be the wallet farming is processed from)
Wallet.
0x644c4A0708aD182dA244DBe00fDc0D19110e6fD3

THREE parts to the proposal.

1. PURCHASE up to $16000 or 1000 HEC tokens which ever format is the cheapest at time of purchase 

2. PLACE The HEC tokens on there staking pool paying between 16/20% APY

3. If the HEC tokens reaches a value of $50.00 the amount is withdrawn with yield made and initial capital swapped back to usdc (profits from the token price and yield will be split 90% treasury and 10% buyback and burn.

4. IF the HEC token dosent reach target sell price within 180 days the token is to stay yielding for a further 180 days. (During this period a new proposal will be made for an exit strategy)

Pros :- 
THE HECTOR INSTITUTE has proven itself to be a well established DAO. They operate on a similar principle to agfi buyback/burn. They just announced they have sponsored BVB (Borussia Dortmand FC) champions league football

HEC TREASURY has over 60,000,000 in wallet and over 30,000,000 in farming services. That's now on the bearish market conditions. A few assets in treasury wallet are the following
BTC 123
ETH 811
QNT 9826
AVAX 29662
MATIC 541626
FTM 1410855
NEAR 59566

it gives Agfi the chance to yield up to 20% on part of our treasury in this continued bear market.

Potential 34000 profit for agfi treasury plus the extra yielded tokens if target price met.

Cons:-
HEC Token is not a stable token. Price is subject to votality.

If target price is not met the token will be yielding for 360 days giving apx 200 HEC but the token maybe worth less than entry price.

Overall my thoughts are we have not much farming going on its potential to yield some hec. I always believe the market will turn aventually also I really like the fact  they are proving themselves in the crypto space in more ways than one.

Hec contract 0x5c4fdfc5233f935f20d2adba572f770c2e377ab0

Hec dashboard
app.hector.network

Many thanks

**Comment by AGFITRUST** [comment]
Hi Cryptobuzz1,

Is the staking is for a minimum period of 180 days or can be remove at the convenience?

The idea is great, I'm just thinking about a serious correction on the market after the mid-term on US if they can handle until there.

Regards

**Comment by Cryptobuzz1** [comment]
There is no time lock the funds in staking pool can be removed at any time.
It is very similar to agfi just cost gas which is less than $0.05

So if a new proposal was made to remove this will not be an issue.

All gas fees for transfers/staking are in FTM but the agfi wallet holds a few FTM.

As for serious corrections they have a healthy treasury spread out amongst 60+ tokens. I dont have a crystal ball all I would say we have funds in other protocols at the momment earning very little it could quite easily happen to them in a serious correction.

**Comment by AGFITRUST** [comment]
Thanks for the update.
If this go to vote, I will be FOR

**Comment by Cryptobuzz1** [comment]
I would like to also make the point. That with this proposal focused on farming the funds should come from Diego's wallet as were all aware he is not working for agfi with no payment operations in place.

Wallet
0x644c4A0708aD182dA244DBe00fDc0D19110e6fD3

Usdc balance 16995. (Which would cover cost of the proposal)

**Comment by Cryptobuzz1** [comment]
Header amended with the changes

**Comment by Cryptobuzz1** [comment]
Juat another thought on this proposal if was successful. If tweeted to there official site maybe 1 of there 75k plus supporters may look into our small market cap AGFI.

**Comment by HuleboerES** [comment]
> Juat another thought on this proposal if was successful. If tweeted to there official site maybe 1 of there 75k plus supporters may look into our small market cap AGFI.

Or, they see us as a FaaS which cannot grow our own treasury, and this is the whole point of AGFI.....

**Comment by AsgaaardFjord** [comment]
After reviewing it, the proposal managers decided to not allow this proposal. Our first mission is to clarifiy if such a proposal could put agfi into peril. We have come to the belief that specific, direct requests for asset purchases place the stability of the Treasury at risk and those decisions should be taken by a professional/delegated trader who has gone through KYC.
