### ISSUE TITLE
15 day execution period on proposals

### ISSUE THREAD

**Issue by Cryptobuzz1** [aggregatedfinance/agfi-dao#14]
Proposal made on behalf of the proposal Managers.

To introduce a 15day window on all proposals submitted.

We feel 15days is long enough to adjust or ammend a proposal to meet all criteria to be APPROVED by the PMs of aggregatedfinance.

Pros-

To create boundaries on all new proposals to be acted upon if they fail to meet criteria for vote.

Enables the project to keep the proposal list in adequate order and prevents a back log of proposals been open on github (clean and tidy approach)

Cons:-

Any new proposer or proposal will have a 15 day window to act upon the obsticals arisen from community or pms. And therefore has a timed window to interact and change the proposal accordingly.

**Comment by AsgaaardFjord** [comment]
I second this. We need some rules and structure. 30days is more than enough to react.

**Comment by HuleboerES** [comment]
30 days is too much, we need to be able to react quicker. I suggest 15 days.

**Comment by Cryptobuzz1** [comment]
Yes we aim to get proposals voted on within this timeframe. It's more the advice given to proposals to be accepted by the PM's and the proposer does not ammend.

**Comment by Cryptobuzz1** [comment]
> 

Thank you for your comments. After taking this point into consideration we believe you have a valid point therefor we agree this should be a 15day window.

**Comment by Cryptobuzz1** [comment]
I have changed the header to 15 days and the PM's have APPROVED this proposal will got to que to vote shortly

**Comment by Cryptobuzz1** [comment]
Proposal opened on snapshot platform.:-
https://snapshot.org/#/aggregatedfinance.eth/proposal/0x644c2ba297ec25a56265720905df7b214b3309568da1883a01b6ec447b9212e9

**Comment by Cryptobuzz1** [comment]
Proposal Passed. 
This boundary/ruling is enforced starting  09/09/22
