### ISSUE TITLE
Treasury - Reallocate Funds from Previous Farmer to Current Farmer

### ISSUE THREAD

**Issue by aggregatedfinance** [aggregatedfinance/agfi-dao#15]
_The amount requested to transfer:_

All assets in the following wallets:
0x4c3ADd465413A85EfcD24a523A3cEb68B7566F95
cosmos1zzfvpqr2kwvxf4x23l8dn5n3vkcyjcpa4rtw52
terra1elzncl4032mvaxyvfynvwwahplp2pfhadj6wd2
thor1uucdcz7nq69mrtxgxy27rg878r78wn0q69pace

_The recipient of the amount. Each additional recipient will receive the specified amount in the proposal:_

0x4c3ADd465413A85EfcD24a523A3cEb68B7566F95

_The purpose of the transfer. This can include the allocation of the funds to delegated traders/farmers, to conduct purchases of specific assets, to perform token buybacks, or to pay external parties for services:_

Allocation of funds to current delegated trader, @eggwards (telegram username).

_Justification for the transfer, if one or any of the recipient addresses are not known to the team:_

Not required.

**Comment by Cryptobuzz1** [comment]
I like the idea . I do believe it should be clarifying the value of these wallets of which ed will end taking control of.

**Comment by LeoKing7777** [comment]
Instead of transferring The funds in only those wallets ? I think we should transfer 75% of the treasury or even 100% if we are happy with EDs transparency and risk management. A 5% gain on 400k is obviously much better than on 120k so why not utilise this market. IMO I anticipate ETH doing a good 15% pump toward the merger date 15th sept 2022. Lot of potential to buy the hype now and sell 1-2 days before.

**Comment by AsgaaardFjord** [comment]
We cant leave the money to much to dust into the wallets slowly decreasing in vlaue. In favor of moving the the funds into the wallet of the delegated trader.

**Comment by AGFITRUST** [comment]
For sure we have to move the funds from Diego wallet and use them to trade more with Ed.

**Comment by Cryptobuzz1** [comment]
This has been approved unanimously by the aggregatedfinance PM's.

This proposal has been moved to vote on snapshot :-
https://snapshot.org/#/aggregatedfinance.eth/proposal/0xba703f9423f38d1f63bdf43f700b8399e6f04a79303e8f17683f50b9c0614936

**Comment by Cryptobuzz1** [comment]
Voting result FOR. Agfi official and trader ed will arrange the transfer
