### ISSUE TITLE
Award Achievement ladder (buyback & Eth reward booster)

### ISSUE THREAD

**Issue by Cryptobuzz1** [aggregatedfinance/agfi-dao#16]
To introduce Award Buyback & ethrewards booster ladder.

On a future successful aggregated finance treasury balance. I have decided to make a proposal to implement an award buyback ladder. The buyback will be authorised if the treasury achieves the ladder targets

Award ladder as follows:-
250k     target =  1000$ BB  ✅ 01/01/01
500k     target = 2500$ BB
750k     target = 5000$ ERB
1mil      target  = 7500$ BB & 7500$ ERB
1.5 mil  target = 7500$ BB & 7500$ ERB
2 mil     target = 7500$ BB & 10000$ ERB
2.5mil  target = 10000$ BB & 10000$ ERB
3 mil     target = 22500$ BB
3.5mil  target = 10000$ BB & 15000$ ERB
4 mil     target = 25000$ ERB
4.5mil  target = 15000$ BB & 15000$ ERB
5 mil     target = 30000$ BB 
6 mil     target = 35000$ ERB
7 mil     target = 20000$ BB & 20000$ ERB
8 mil     target = 45000$ BB
9 mil     target = 50000$ ERB
10 mil  target  = 50000$ BB & 100000$ ERB

BB=Buyback ERB=Eth Rewards Booster

All buybacks to be put back into the dao treasury and the use of these tokens can be voted upon in due time. This will eliminate the views of what's best ie pay trader, burn or use as liquidity.

Eth rewards boosters are on the ladder to be an incentive for holders to hold when the time arrives when target is met.

The ladder can be displayed in main every time a target as been achieved and actioned can be ticked and dated as example above on ladder to deny any repetiveness of the target been achieved.

To give permission to delegated trader to action the buyback reward if achieved and to transfer funds into the eth reward contract if achieved.

Pros:- adds an incentive to the project over the coming years.
Another way of attracting new investors.

Cons:- using part of the treasury of which we are trying to build.

**Comment by Melkorious** [comment]
How does this proposal take into consideration the varying fiat valuation of one Eth?

Leaving the buy/sell period up to the Custodian forces the Custodian to speculate on the best time to purchase Eth - which is not the Custodian's role.

**Comment by Cryptobuzz1** [comment]
It does not take the fiat value into consideration the terms of the ladder are in eth (1 eth = 1 eth)

As for the action of the buyback I'm not sure would there be another way around this maybe delegated Trader can action the achievement if successful. I.believe a window is better compared to action as soon as achieved.

**Comment by Melkorious** [comment]
I think you're better off equivocating the buyback value in $USD - especially considering Eth's 52 week range is so wide. If Eth is $10,000 a coin for example, the Buybacks become a little nutty.  Conversely, if Eth is $600 a coin, the Buyback is not meaningful.

Additionally, it's probably wiser to have the Delegated Trader execute the Buyback since they control the Treasury funds, anyway.

Also - what is being done with the Buybacks in this Proposal?  Is it Buyback and Burn?  Buyback and replace tokens to Liquidity Pool?  Buyback and Hodl for future use? 

As far as the window is concerned, I don't think you want someone being held accountable for making the decision to Buyback or not - if it goes the wrong way, they'll be responsible for losing buying power.

**Comment by Cryptobuzz1** [comment]
I see what your getting at with the fiat price of eth it may be worth more than what our treasury balance is If we was not holding any eth in the treasury. I've revised the ladder to dai. Then this can be converted to the the value of eth at the time of achievement.

**Comment by Cryptobuzz1** [comment]
Maybe buyback and burn any other thoughts on what to do with the buyback as  mentioned above? 

Need help.with how to execute the award if successful. Will it be best just doing the buyback as soon as an award has been achieved ?

**Comment by AGFITRUST** [comment]
It's a very good idea, even the window for the buyback is a great thing too.
Do it exist and is it possible to ad an option for the buyback time (like a lottery, to determine a buyback day between 30 to 60 days) without result until the buyback action. Like this we have more exposure to buy and sell action

**Comment by LeoKing7777** [comment]
I personally never been a fan on buybacks and they proven to be useless from other projects and even doing it with AGFI previously.

First if we did, we should use USD and not ETH, ETH is way to unpredictable. Also what's a $2,500 or $5,000 going to achieve ? It's like a piss in the ocean. May as well give it to the trader as commission when that kicks in and reduce our outgoing cost. My point is spend it on something that will give us best value for money and impactful to the project.

**Comment by Melkorious** [comment]
Leo does have a point concerning the efficacy of Buybacks.

For the overwhelming most part, people just use the Buybacks for exit liquidity, especially in a bear market.

In a Bull Market, Buybacks shouldn't be necessary.

I think what you've done here however, is sparked a good conversation concerning what to do with profits when they do start rolling in.

It is technically true that a price floor can be established via Buybacks - but it would take a considerable amount of $USD dumped into the LP to make that floor move upwards in any meaningful capacity.  Bear in mind, there are quite a few "AGFI billionaires" that would dump with a 25% price pump.  So ask yourself, how much $USD would it take to move the price 25% up, and then how fast would it be sucked out of the LP via a jeet?

**Comment by Cryptobuzz1** [comment]
In this case we could use the buybacks as a hold and it will in turn be paid as commission towards trader or possibly traders in the future. Either way a buyback on agfi will be volume and therefor 12% of the buyback goes into the taxc channels aswell. Treasury. Ethrewards & operations

**Comment by Cryptobuzz1** [comment]
Also at the level of the floor price as is now this would be welcoming news. 

Anything moving up 40% plus in a day always makes top ten on cmc coingecko etc and of this was to happen it attracts eyes to have browse.

**Comment by Cryptobuzz1** [comment]
I've updated the ladder with extra awards. The buybacks will be held to help pay trader/traders commission fees.
Now also added ethrewards booster at certain levels to boost a holders rewards another incentive to hold

**Comment by eggwards** [comment]
Hello would it be possible to reinvest the money that should be going for buy backs in sponsorships and marketing? I feel that while $1000 is basically nothing when it comes to buybacks it can get us quite a bit of exposure if we invest it in some form of advertising.

**Comment by Cryptobuzz1** [comment]
> Hello would it be possible to reinvest the money that should be going for buy backs in sponsorships and marketing? I feel that while $1000 is basically nothing when it comes to buybacks it can get us quite a bit of exposure if we invest it in some form of advertising.

It was more of an incentive as an award ladder. During the laying the foundations so to speak. It adds an incentive to the loyal holders of agfi during these times.

I would like to think that buybacks and hold help the project in every aspect as a holder and as a project to help pay wages.

As for sponsorships could this not be proposed separately when the treasury has got a healthy balance or maybe asked to use from operations tax channel.

**Comment by Cryptobuzz1** [comment]
Has anyone else have any ideas of awards which could be introduced on the ladder to help the project.

**Comment by Cryptobuzz1** [comment]
To eliminate what's best to do with the buybacks. All buybacks if achieved will be placed back into the dao treasury.  This way it eliminates the debate of the usecase of the buyback.

Now buybacks  returni to the Dao treasury the tokens can be voted on a different proposal of what you would like to do with them all be it burn them use them as commission or replace liquidity the options are available.

I've amended the main proposal with the change in buyback destination.

**Comment by Cryptobuzz1** [comment]
Voting opened:- 
https://snapshot.org/#/aggregatedfinance.eth/proposal/0x3a41cface02ede00f640f1100240aaede4db004a8cb952eb5c7c14b3b5464d43

**Comment by Cryptobuzz1** [comment]
Vote closed , result successful.
Ladder to be published in main. Trader to action rewards 
This proposal is  now closed as complete
