### ISSUE TITLE
Management - AGFI Tax Changes

### ISSUE THREAD

**Issue by Cryptobuzz1** [aggregatedfinance/agfi-dao#17]
Modify Agfi Tax on Buys and Sells

To reduce total taxes by 28% 

Apply a 5% tax on buys (currently 12%)
Leave sell tax at 13% change the parameters.(currently 13%)

As mentioned in main to try generate extra volume. Proposal made to change tax % and change tax chanel distribution:-

Buys 5% :-
1% operations 
4% treasury

Sells 13% :-
6% treasury
3% rewards
3% operations 
1% autoburn

The idea behind the change is to hopefully create extra buy pressure inturn creating volume.

Pros:- Lower buy tax to increase volume 
Cons:- less eth rewards distributed to holders.

This proposal is more to see if lower taxes on buys will gain volume. Most members feel rewards can be added back in the future. Also think the rewards are better invested to treasury giving trader the chance to build treasury at a faster pace.

**Comment by Melkorious** [comment]
How does this reduce taxes by 28%?

**Comment by Cryptobuzz1** [comment]
At the moment taxes are 25% the reduction takes it to 18% total taxes, which is the equivalent of a 28% reduction in total taxes.

**Comment by AGFITRUST** [comment]
After closing staking, the reward became 4,5%, the idea to remove from buy taxe is OK but from sell taxe better to be 4,5% if remove all the holders taxe, its no more points to hold agfi like on the beginning.
Remember last time you where saying no buyback to burn from trade profit...
If you remove or reduce too much taxes for holders and never buy back , what's the point to hold?

Thanks

**Comment by Cryptobuzz1** [comment]
> After closing staking, the reward became 4,5%, the idea to remove from buy taxe is OK but from sell taxe better to be 4,5% if remove all the holders taxe, its no more points to hold agfi like on the beginning. Remember last time you where saying no buyback to burn from trade profit... If you remove or reduce too much taxes for holders and never buy back , what's the point to hold?
> 
> Thanks

A change in the distribution is not a problem. The answer to your question why hold. Idea is to get treasury up faster so trader has more funds to play with inturn will get reward ladder into play.

**Comment by Cryptobuzz1** [comment]
Anymore thoughts in sell tax distribution?

**Comment by CryptoNielsB** [comment]
I agree on the tax change but would change the Sell tax to:
Sells 13% :-
6% treasury
3% rewards
2% autoburn
2% operations

Just my 2 cents.

**Comment by Cryptobuzz1** [comment]
> change

The more input the better thanks for spending a few moments with your thoughts

**Comment by LeoKing7777** [comment]
I think the ETH rewards is only good with volume. So for it to be more attractive to buy AGFI there would be more upside from the price impact than the rewards. It's a Good idea to change buy tax to 5% and sell tax should be 8% treasury 4% operations to allow for a future marketing cushion.

**Comment by Cryptobuzz1** [comment]
> to

I understand your views on eth rewards, however before posting the proposal we had a discussion with the comunitee and 70% did mention they would be happy to take a drop in % but most felt uncomfortable to not have any rewards completely 

Also with operations and future marketing this is a very important subject and will put an extra 1% on sells and reduce treasury on sells to 6%.

We also have to remember these taxes can be changed with any new proposal if circumstances change within the project. 

But to have better chances of this proposal being approved by holders the eth rewards on sells will stay the same 3% .

**Comment by Cryptobuzz1** [comment]
Origional proposal tax channel allocations changed to the following:-

Buys 5%
1% operations 
4% treasury 

Sells 13%
3% operations 
3% rewards
6% treasury
1% autoburn

**Comment by CryptoNielsB** [comment]
Sounds good !

**Comment by Melkorious** [comment]
This Proposal is clean.  I'd approve to advance to vote.

**Comment by AGFITRUST** [comment]
Nice proposal like this, will vote for

Let's just make sure to advertise on twitter after with a lot of retweet

Thanks to you

**Comment by Cryptobuzz1** [comment]
Proposal passed by Agfi Pm's.

Opened for vote on snapshot:-
https://snapshot.org/#/aggregatedfinance.eth/proposal/0x2c90768fb0d227c5fb2460b55a75cc6e40dd8f342dd3dd50f6045f31af72128f

**Comment by aggregatedfinance** [comment]
Proposal changes executed based on vote outcome:

https://etherscan.io/tx/0x6fc293a0e0f9caa0fc3955d8cc3b64839f3e74a6b1baf08ef5184f28e6f7782e
https://etherscan.io/tx/0xc55f9d94affb5a676e2383cff1d4d2ba791df45b520539db4da0e27c789496e0
