### ISSUE TITLE
Treasury - Alternative Chain Token

### ISSUE THREAD

**Issue by aggregatedfinance** [aggregatedfinance/agfi-dao#3]
_The amount requested to transfer:_

5 ETH

_The recipient of the amount. Each additional recipient will receive the specified amount in the proposal:_

0x3e822d55e79ea9f53c744bd9179d89ddec081556 on the destination network (and in equivalent base currency converted from the 5 ETH)

_The purpose of the transfer. This can include the allocation of the funds to delegated traders/farmers, to conduct purchases of specific assets, to perform token buybacks, or to pay external parties for services:_

To establish the Aggregated Finance token contract on an alternative chain.

_Justification for the transfer, if one or any of the recipient addresses are not known to the team:_

Aggregated Finance deployed on an alternative chain would provide more users seeking the use the protocol on a chain that is cheaper to transact with.

The alternative chain tokens would be excluded from DAO voting. DAO votes would only be performed with Ethereum AGFI.

Some outstanding questions:

- Should there be a bridge between the two networks for the tokens? This would mean current Ethereum AGFI holders would be able to exchange their AGFI for the alternative chain AGFI, and cross-chain arbitrage trading would occur equalising the token prices. If there was no bridge, the two tokens would remain independent of each other.
- What will the launch price/liquidity be for the alternative chain?
- What should the destination chain be? Binance Smart Chain? Fantom?
- Should all tax channels be replicated on the alternative chain? Should the percentages remain the same?
- Should DAO functionality be removed entirely from the contract, or preserved to provide options in the future?

**Comment by IgorBogdanoff420** [comment]
Igor think second chain good for people put off by gas fees. Thinks DAO interaction should be retained if possible.

**Comment by Peertosh** [comment]
I think BSC chain should the second chain.

**Comment by Zaphods-Ghost** [comment]
I would like to stay as far from BSC as possible.. There are other good projects out there, no need to dip into the meme coin world  of BSC.

Skale, Hedera, Elrond are some very strong options.

**Comment by AGFITRUST** [comment]
Good idea to have an other chain, but we have to make sure to bridge, like this people from eth will continue to enjoy reward.
For admin: 
-Is the contract able to cross chain? 
-Reward can follow?
-can people vote from other chain?

Our target is to bring volume for actual and future holders, let's make sure the future chain will expose current holders to volume, not just an arbitrage without rewards.

**Comment by Peertosh** [comment]
Should DAO functionality be removed entirely from the contract, or preserved to provide options in the future?
=> The contract should defenitely preserved the DAO otherwise the usp of the token is gone.

**Comment by LeoKing7777** [comment]
What about moving to Matic/Polygon- recent news Polygon has partnered with Meta to create an NFT platform for Instagram and Facebook, Polygon CEO Ryan Wyatt announced via Twitter.

The partnership will expose Polygon’s blockchain ecosystem to Meta’s combined 2.9 billion users. Wyatt said Meta chose Polygon due to its carbon-neutral footprint and high scalability.

**Comment by Melkorious** [comment]
If this proposal is to explore another chain - then it's fine to move to vote.

That said, if this proposal is looking to answer all of the proposed questions in the OP, then the "answers" must be presented in the proposal prior to being approved to being voted on.

Advise.

**Comment by Cryptobuzz1** [comment]
Due to proposal #14 being successful this proposal has been closed due to the new 15 day rule which went live 09/09/22
