### ISSUE TITLE
Treasury - [Staking ETH]

### ISSUE THREAD

**Issue by Peertosh** [aggregatedfinance/agfi-dao#4]
Investing idea for our Treasury. 
MCC offers ETH Staking and earning MPRINT. APR is currently 600%.

My proposal:
Use ETH from the AGFI Treasury for staking ETH for MPRINT

**Comment by bedjackhammer** [comment]
Anything that can offer those returns are a positive. Let’s do it.

**Comment by Zaphods-Ghost** [comment]
Where do their Staking rewards come from?   I am not sure MCC has shown to be a model we want AGFI to mimic...

**Comment by Peertosh** [comment]
> Where do their Staking rewards come from? I am not sure MCC has shown to be a model we want AGFI to mimic...

The topic isnt to mimic mcc. Its just to expand our treasury. I guess the staking rewards comes from the mcc treasury.

**Comment by Melkorious** [comment]
This proposal does not adequately outline how to accomplish the staking model being suggested.

**Comment by Peertosh** [comment]
> 

Go to https://mprint.mchain.capital/ connect wallet, change eth in weth then you can stake weth for mprint

**Comment by aggregatedfinance** [comment]
It seems there is legal action being opened against the MCC project. There may be an underlying risk to AGFI by interacting with a project that may suffer interference from authorities from these legal proceedings.

https://t.me/MultiChainCapital/1034394

**Comment by Cryptobuzz1** [comment]
Stay well away and pull mcc out of the wallet then?

**Comment by aggregatedfinance** [comment]
> Stay well away and pull mcc out of the wallet then?

A vote can be made on snapshot to vote on liquidating that position if it's wanted

**Comment by Cryptobuzz1** [comment]
Due to proposal https://github.com/aggregatedfinance/agfi-dao/issues/14 being successful this proposal has been closed due to the new 15 day rule which went live 09/09/22
