### ISSUE TITLE
Cancel staking rewards and allocate more eth rewards/treasury

### ISSUE THREAD

**Issue by AsgaaardFjord** [aggregatedfinance/agfi-dao#5]
The latest vote showed clearly that staking clearly damages the voting power. In the end we are a dao and should be out working product. Finding a workaround to stake and vote will cause other problems
A further downside is the gasfees, especially for the holders with lower tokens.

My proposal instead:

Cancel the staking rewards tax and allocate those tax 50% to eth rewards and 50% to treasury

Eth rewards are way.more interesting as it doesn't affect the.price of agfi and can be easy accumulated by only holding

A big treasury allows us further options to move forward with the project.

**Comment by IgorBogdanoff420** [comment]
So there would be no benefit to staking anymore? Certainly makes more sense as an idea as the DAO is supposed to be our selling point and there's too much confusion currently.

**Comment by AsgaaardFjord** [comment]
We can also reallocate the 3% to the eth rewards l, but staking in it's current situation blocks future proposals. We barely made the very first one

**Comment by AGFITRUST** [comment]
Really not a bad idea, more votes can be more healthy for the dao.

**Comment by Melkorious** [comment]
@AGFITRUST - Do you use Telegram?  Me and the other PM (Aria) have started a private group to discuss proposals.

**Comment by Melkorious** [comment]
This proposal is adequate.  Can be moved to vote.

**Comment by AGFITRUST** [comment]
Yes, my telegram name is antho.
Please let me know the name or the link for this group, I will join.
Thanks

**Comment by Cryptobuzz1** [comment]
I'm a great believer in choice and find staking very attractive for agfi. Yes voting may of been (slow to particupation) .However when something is up for vote which is highly opinionated I'm sure they will turn out to vote.

**Comment by aggregatedfinance** [comment]
Under advice from @Melkorious proposal has been opened on Tally: https://www.tally.xyz/governance/eip155:1:0xD243F9aAfCf32e60b2e9D0FF016cf7f1552d5952/proposal/10420887434633643397811781666774699238175141327232564620701769386242677800892

**Comment by aggregatedfinance** [comment]
Proposal passed. Queued for execution now. As the execution will not modify the contract, the modifications have been made by the custodian instead:

New contract channel parameters:

buyC1Fee 550
buyC2Fee 0
buyC3Fee 450
buyC4Fee 0
buyC5Fee 200
Total Buy Fee 1200

https://etherscan.io/tx/0x36aaabd444459e98071e51210529842255012b0c0187c7e74e0520d391d13b41

sellC1Fee 550
sellC2Fee 100
sellC3Fee 450
sellC4Fee 0
sellC5Fee 200
Total Sell Fee 1300

https://etherscan.io/tx/0xb8daae5f04069f4dff619ef031f6d0170cf9fd0ba0496e382b8a9c34bd3b4bd9

<img width="190" alt="image" src="https://user-images.githubusercontent.com/101265123/179381856-2dfde326-00f9-4570-86ee-7d7fd47607a3.png">

<img width="207" alt="image" src="https://user-images.githubusercontent.com/101265123/179382192-07b5acd8-024f-4503-a607-8a37736b4c5d.png">
