### ISSUE TITLE
Treasury - Allocate ETH to Trading Bot

### ISSUE THREAD

**Issue by aggregatedfinance** [aggregatedfinance/agfi-dao#7]
_The amount requested to transfer:_

$15k worth of ETH or stablecoins from the treasury already allocated to delegated trader @Eggwards

_The recipient of the amount. Each additional recipient will receive the specified amount in the proposal:_ 

0x4c3ADd465413A85EfcD24a523A3cEb68B7566F95

_The purpose of the transfer. This can include the allocation of the funds to delegated traders/farmers, to conduct purchases of specific assets, to perform token buybacks, or to pay external parties for services:_

The community will purchase access to the DEX signals service https://unism.art/. The wallet will execute trades according to the bot signals for the treasury.

Pros:

- Signals services are unbiased, reducing potential community disagreement about specific trades.
- The community can follow all trades via the treasury dashboard.
- Moderate risk to the treasury.

Cons:

- This is not farming, this is trading. This would be a vote for the community to expand outside of farming-as-a-service.
- Some signals can fail, and stop losses must be executed to minimize losses.
- Moderate risk equals moderate returns.
- Limited to DEX trades only.

_Justification for the transfer, if one or any of the recipient addresses are not known to the team:_

Not required.

**Comment by LeoKing7777** [comment]
I think this is a great idea, we should allow the bot to trade L1s that are low risk but with great potential to move up on positive market momentum. In addition, I also think we need another manual trader with strong knowledge of crypto space and trading in general to manage part of the treasury to be paid AGFI from our 100b AGFI tokens we have held in the treasury.

**Comment by Phenol0477** [comment]
I also agree to this. I believe the higher the level of accuracy of the bots makes them a good backing for this trading activities. However, I would also recommend that we also complement the signals with our own technical analysis to increase the level of efficiency and success of the trading. Maybe someone could volunteer for that also.

**Comment by Peertosh** [comment]
Good idea. I will vote for this!

**Comment by Zaphods-Ghost** [comment]
I like the idea, i believe a conversation about what Signals to use is warranted as a particular service it is stipulated in the proposal.

Also the person responsible for the trades needs to be defined as well.   They cannot have a say in the trades, when a signal arrive, it just needs executed regardless of their personal opinion of the trade.

**Comment by aggregatedfinance** [comment]
> I like the idea, i believe a conversation about what Signals to use is warranted as a particular service it is stipulated in the proposal.

> Also the person responsible for the trades needs to be defined as well. They cannot have a say in the trades, when a signal arrive, it just needs executed regardless of their personal opinion of the trade.

To address both of these items, lets adjust this proposal to start with a smaller amount of $15,000 worth of ETH. This way it minimizes risk for proving if this strategy is viable, and future votes can be applied to increase or cease this option.

Executor of the trades will be the DAO custodian unless a delegated trader is voted in.

**Comment by Cryptobuzz1** [comment]
Yes this is a much better approach to the trading bot.

**Comment by Melkorious** [comment]
Now that a Delegated Trader has been selected, this Proposal can be pushed to vote.

**Comment by Cryptobuzz1** [comment]
Thank you everyone for playing your part on github. Can we que this proposal on snapshot please .

**Comment by Cryptobuzz1** [comment]
If the proposer can ammend the initial investment title  from 30k to 15k this proposal meets the criteria and can be queue for voting please.

**Comment by eggwards** [comment]
Hello everyone as I am the delegated trader already and also have quite a bit of experience with bots I could manage this stuff with choosing and managing funds on the bots.

**Comment by HuleboerES** [comment]
Can proposer(if interested) ammend the initial investment title from 30k to 15k on this proposal?   As [Cryptobuzz1] also mentioned.

**Comment by aggregatedfinance** [comment]
Amended parameters to reduce to $15k and allocate from the treasury in control by @eggwards. Proposal now queued on Snapshot:

https://snapshot.org/#/aggregatedfinance.eth/proposal/0xb92ecc74e6ce192a85468f5a7d878f4df39863c094a5b48563c6d06164a3a2c7

**Comment by Cryptobuzz1** [comment]
Vote closed result successful. 
Trader has now permission to purchase bot
