### ISSUE TITLE
Treasury - Stable Fund Investment (Polygon)

### ISSUE THREAD

**Issue by L3nn3rs** [aggregatedfinance/agfi-dao#8]
The amount requested to transfer: 

**15k in Matic on Polygon Network**

The recipient of the amount. Each additional recipient will receive the specified amount in the proposal: 

**A Stable Fund account will need to be created and funds transferred to the wallet so these can be invested for a daily return of 1.5%.**

The purpose of the transfer. This can include the allocation of the funds to delegated traders/farmers, to conduct purchases of specific assets, to perform token buybacks, or to pay external parties for services: 

**Stable Fund is an investment platform which provides 1.5% on initial investment which is locked for a period of 28 days, each day the rewards can be claimed and either withdrawn or reinvested (compounded), the latter will then be locked for a further 28 days (48% return on investment at this stage).** 

**The current return on initial investment is 49 days, I would propose that the initial investment is compounded to this point and then withdrawn and placed back into the Treasury, the remaining 23k Matic should then be compounded for at least 5 months which will return 200k Matic. The Polygon network is currently full of hype and lots of talk about things happening in the near future, in the last week it has increased 48% so assuming the same over the next 6 months would result in the initial investment returning $200k and due to the initial investment being returned to the Treasury very low risk.**

**Crazy numbers but if this 15k Matic risk free investment was invested for 365 days it would be worth 4.3m Matic, in that period Matic could be in excess of $2 ($8.6m) so a superb return all risk free after 28 days.**

**I already compound my own investment daily so would be happy to do the same for another investment under a separate wallet, as above open to agree how this can be multi-sig (if possible?). The initial account will need to be made with an email and password before wallet can be added to hot wallet, although this is not required other than bridging funds.**

Justification for the transfer, if one or any of the recipient addresses are not known to the team:

**Pros**

- Dev is fully doxxed and active in the telegram, does weekly AMA and is quick to respond to any fud!
- v1 of Stable One had an issue with the contract and investors were unable to rewards funds, the Dev paid all those impacted out of his own funds - I was one so can vouch for this.
- StableOneGroup is a limited company in the UK (Company number: 14099508).
- The trading is carried out by AI contracts which have been running three years, this is not a ponzi scheme that relies on new money.
- Stable Fund live since April 2022.
- The fiduciary wallet holds in excess of $23m, images shared within the last AMA (see pinned message 98 in Telegram)
- In addition to Matic fund there is also BUSD

**Cons** 

- Requires someone to compound daily
- Matic price could drop after investment
- Relatively new to investors
- Might not last 28 days (albeit now on month four with fiduciary wallet increasing exponentially)

I want to share this with everyone because from what I have heard and seen it looks and feels very legit, I have dropped all the links below so you can all do some further research. Check it out maybe invest 10 Matic and see what you think.

https://stablefund.app/

Stable Fund apps also available on Apple and Android, these are pretty impressive wallets and have a range of features currently live with more coming in the next month.

Final note - it would be good to agree a fixed period to compound and then how a percentage of these rewards are distributed to OG holders.

Any Qs let me know.

**Comment by Cryptobuzz1** [comment]
I like this idea 1.5% on stables is better than 0. Great point about treasury gets investment back after 49 days and play with profits . I also believe in 8 months time with the 2023 launch of zk roll up the value of matic should be in a good position either way we hold matic.

**Comment by LeoKing7777** [comment]
I like this as I am a big fan of Matic and what they have built, however I need to understand how this app works and if it's feasible to be managed daily. Also, not sure if the current price is a good entry given the recent pump and possible further market downside as this could just be a bull run within a bear market. Maybe DCA every week or so Would be a good idea. 48% guaranteed return is a no brainier and consistent, but I wonder how safe this is - we don't want another Celsius 2.0

**Comment by AGFITRUST** [comment]
Really interesting idea.
Let's vote for it, wait for a correction and enter this position

**Comment by aggregatedfinance** [comment]
> this is now a ponzi scheme that relies on new money.

Is this correct? If so this does not seem like a pro for the service. Please provide a clarification for this to be taken to vote.

In addition, is there a risk of assets being seized by the service (similar to Celsius stopping users from withdrawing)?

**Comment by L3nn3rs** [comment]
> > this is now a ponzi scheme that relies on new money.
> Is this correct? If so this does not seem like a pro for the service. Please provide a clarification for this to be taken to vote. 

**I have updated the proposal it should have read not a ponzi**
 
> In addition, is there a risk of assets being seized by the service (similar to Celsius stopping users from withdrawing)?

**This is always a risk, I can't say that it won't happen but I and many others have been withdrawing capital after 28 days since the beginning of April 2022**

**Comment by Melkorious** [comment]
This Proposal is clear to move to vote.

**Comment by LeoKing7777** [comment]
I think - the risk is too large now to take 25k, once we make like 500k then such risk are more suitable, we don't know much about this fund and nor can we fully trust it. Lot of exchanges are getting in trouble and scamming ppl so as much as I like polygon, I would hold this for future and ask the trader , to decide or operate this.

**Comment by aggregatedfinance** [comment]
As the amount may conflict with the allocation proposed in #10, this will be reevaluated after #10 finishes its vote.

**Comment by Cryptobuzz1** [comment]
Lenners looking at some of the feedback may be lower the amount requested.

And maybe suggest an exit strategy

**Comment by L3nn3rs** [comment]
**Hi all, I have reviewed all the comments above and propose to invest 15k returning the initial investment to the treasury at the end of October and compounding the balance rewards daily until end of March 23 which should return approx. 200k Matic. 75% returned to treasury with 25% used for a buyback.** @aggregatedfinance @Cryptobuzz1

**Comment by Cryptobuzz1** [comment]
Hi lenners. Thank you for your update on this amendment you will need to edit your main title to 15k on the first post instead of 25k.

**Comment by Cryptobuzz1** [comment]
Lastly to eliminate doubt of A.N.Other person with access to funds on this particular proposal. Now we have a delegated trader. Would he be happy to volanteer to action the duties of this proposal (compounding withdrawing etc) .

**Comment by eggwards** [comment]
Hello, I'd be happy to manage the funds on stable fund if the proposal passes.

**Comment by Cryptobuzz1** [comment]
Proposal opened on snapshot:-

https://snapshot.org/#/aggregatedfinance.eth/proposal/0x41225d7e03101e27373803651b8741a1708fdd9d554b9237cf6d51a0e0acc43c

**Comment by L3nn3rs** [comment]
Great news @eggwards 👏

**Comment by Cryptobuzz1** [comment]
Vote closed with majority AGAINST outcome. This proposal is now closed as complete.
