### ISSUE TITLE
Treasury - Swap $24,000 DAI for ETH at Target Price $800

### ISSUE THREAD

**Issue by Cryptobuzz1** [aggregatedfinance/agfi-dao#9]
_The amount requested to transfer:_

$24000

_The purpose of the transfer:_

Whilst we have no farmer/trader. I would like to propose the following future trade if the target price is achieved!

Actions:

- If ETH falls to $800, swap $24000 of DAI from the treasury to ETH
- Target price $1600 - swap 15 ETH back to DAI. Retain 15 ETH in the treasury.
- Swap and burn 2.5 ETH of AGFI if sell target reached.
- Time limit: 90 days after vote completion. After 90 days this action is considered invalid.
- No stop loss defined for the purchased ETH. A separate vote will need to be performed to change the sell targets.

Further notes:

If Agfi appoint a new trader/farmer before the entry price is achieved. The new Trader/farmer will execute the trade on behalf of proposal #9 to the same value with which ever token he wishes from the treasury.

_The recipient of the amount:_

N/A - Action to be performed by aggregatedfinance.eth

**Comment by AGFITRUST** [comment]
Very good proposal, I agree 100%

**Comment by Peertosh** [comment]
Good proposal! IMO we wont see $800 for eth

**Comment by Cryptobuzz1** [comment]
I changed the title as I was made aware of a spelling mistake.

**Comment by Melkorious** [comment]
How long does the proposal suggest it should be valid for?  If the Proposal passes, but an $800 ETH price point doesn’t ever come…how long before the Proposal is voided?  Please update.

**Comment by Cryptobuzz1** [comment]
I have taken the advice into consideration and therefor I have amended the proposal to be valid for 90 days from day of a successful vote .

**Comment by aggregatedfinance** [comment]
Amended the proposal information for clarity and to define the actions more clearly. Moving this to snapshot for vote as the timelock treasury does not need to release any funds to execute this.

**Comment by aggregatedfinance** [comment]
Proposal opened on Snapshot:
https://snapshot.org/#/aggregatedfinance.eth/proposal/0x72bb8df7f20a5d9e782c9f473115c55e4a4f1f64c5a2743f35eaf6f1c908d64c

**Comment by aggregatedfinance** [comment]
Vote closed with a majority FOR outcome. Market will be monitored until 31st of October 2022 to determine if ETH target entry price is met.
